@host = http://localhost:4000

### -*******************************************************************************-
# USER ROUTES
# Get all users
GET {{host}}/users

###
# Register user
POST {{host}}/users
Content-Type: application/json

{
  "name": "Alina",
  "email": "alina@gmail.com",
  "password": "Alina12345",
  "birthdate": "2003-05-17T21:00:00",
  "roleId": "2"
}

### -*******************************************************************************-
# FLIGHTS ROUTES
# Get flights
