@host = http://localhost:4000

### -*******************************************************************************-
# USER ROUTES
# Get all users
GET {{host}}/users

###
# Register user
POST {{host}}/users
Content-Type: application/json

{
  "name": "Alina",
  "email": "alina@gmail.com",
  "password": "Alina12345",
  "birthdate": "2003-05-17T21:00:00",
  "roleId": "2"
}

### -*******************************************************************************-
# FLIGHTS ROUTES
# Get flights
GET {{host}}/flights


###
# Delete flight by id
@flightId = 3
DELETE {{host}}/flights/{{flightId}}


### -*******************************************************************************-
# BOOKINGS ROUTES
# Book a flight
@userId = dece
POST {{host}}/bookings
Content-Type: application/json

{
  "flightId": "2",
  "userId": "{{userId}}",
  "bookingDate": "2024-06-05T23:28:16.324Z"
}

###
# Get booking by user id
GET {{host}}/bookings?userId=dece&_embed=flight
